<?php
/**
 * @file
 * development_settings.features.user_permission.inc
 */

/**
 * Implements hook_user_default_permissions().
 */
function development_settings_user_default_permissions() {
  $permissions = array();

  // Exported permission: 'access devel information'.
  $permissions['access devel information'] = array(
    'name' => 'access devel information',
    'roles' => array(
      'anonymous user' => 'anonymous user',
      'authenticated user' => 'authenticated user',
      'super-administrator' => 'super-administrator',
    ),
    'module' => 'devel',
  );

  // Exported permission: 'execute php code'.
  $permissions['execute php code'] = array(
    'name' => 'execute php code',
    'roles' => array(
      'super-administrator' => 'super-administrator',
    ),
    'module' => 'devel',
  );

  // Exported permission: 'switch users'.
  $permissions['switch users'] = array(
    'name' => 'switch users',
    'roles' => array(
      'super-administrator' => 'super-administrator',
    ),
    'module' => 'devel',
  );

  return $permissions;
}
