<?php
/**
 * @file
 * Code for the Base Modules feature.
 */

include_once 'common_base_modules.features.inc';

/**
 * Implements hook_init().
 */
function common_base_modules_init() {
}

/**
 * Implements hook_form_alter().
 */
function common_base_modules_form_alter(&$form, &$form_state, $form_id) {
  // On the Maillog settings form, disable the "allow e-mails to be sent",
  // "Create table entries in maillog table for each e-mail" and "Display the
  // e-mails on page using devel module (if enabled)" checkboxes - they will be
  // pre-set in /configuration/[environment].settings.php.
  if ($form_id == 'maillog_admin_settings') {
    $form['disabled_info'] = array(
      '#type' => 'markup',
      '#markup' => '
        <div class="messages warning">
          <h3>' . t("What's going on here?") . '</h3>
          <p>' . t('The options on this page have been disabled as they are configured automagically for your server environment; e-mails will not be sent in local, development, and staging server environments.') . '</p>
          <p>' . t('You can check which environment this instance of this website is set to on the !greyhead_environment_settings_page_link.', array('!greyhead_environment_settings_page_link' => l(t('development environment warning settings page'), 'admin/config/system/environment-warning/'))) . '</p>
        </div>',
      '#weight' => -1,
    );

    $form['maillog_send']['#disabled'] = TRUE;
    $form['maillog_send']['#value'] = $form['maillog_send']['#default_value'];

    $form['maillog_log']['#disabled'] = TRUE;
    $form['maillog_log']['#value'] = $form['maillog_log']['#default_value'];

    $form['maillog_devel']['#disabled'] = TRUE;
    $form['maillog_devel']['#value'] = $form['maillog_devel']['#default_value'];
  }
}
